# Generated by Django 3.0.6 on 2020-05-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20200526_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
        migrations.DeleteModel(
            name='lendbook',
        ),
        migrations.DeleteModel(
            name='lends',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
